# Generated by Django 5.2 on 2025-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(null=True)),
                ('empname', models.CharField(max_length=100)),
                ('empaddress', models.CharField(max_length=200)),
            ],
        ),
    ]
